#!/usr/bin/env node
/**
 * Re-syncs cafe data (address, coordinates, photo, rating, website, phone)
 * from the Google Places API and prints the SQL to apply.
 *
 *   node scripts/sync-places.mjs > supabase/migrations/<ts>_resync_places.sql
 *
 * Reads GOOGLE_MAPS_ANDROID_API_KEY from .env. Requires "Places API (New)"
 * enabled on the Google Cloud project.
 *
 * Cafes with a google_place_id are looked up directly by that id; any without
 * one fall back to a text search on "name, address", which is how the ids
 * were obtained in the first place. Feed it the current table as JSON:
 *
 *   [{ "id": "<uuid>", "name": "...", "address": "...", "google_place_id": "..." }]
 *
 * on stdin, so this never needs database credentials of its own.
 */
import fs from 'node:fs';

const KEY = (process.env.GOOGLE_MAPS_ANDROID_API_KEY ??
  fs.readFileSync(new URL('../.env', import.meta.url), 'utf8')
    .match(/^GOOGLE_MAPS_ANDROID_API_KEY=(.*)$/m)?.[1] ?? '')
  .trim()
  .replace(/^['"]|['"]$/g, '');

if (!KEY) {
  console.error('GOOGLE_MAPS_ANDROID_API_KEY not set (env or .env)');
  process.exit(1);
}

const FIELD_MASK = [
  'id',
  'displayName',
  'formattedAddress',
  'location',
  'rating',
  'userRatingCount',
  'websiteUri',
  'nationalPhoneNumber',
  'photos',
].join(',');

/** The photo `media` endpoint 302s to a durable googleusercontent URL; storing
 * that instead of the API URL keeps the key out of the database and off the
 * wire on every image load. */
async function resolvePhoto(photoName, maxWidthPx = 1200) {
  const res = await fetch(
    `https://places.googleapis.com/v1/${photoName}/media?maxWidthPx=${maxWidthPx}&key=${KEY}`,
    { redirect: 'manual' }
  );
  return res.headers.get('location');
}

async function lookup(cafe) {
  if (cafe.google_place_id) {
    const res = await fetch(`https://places.googleapis.com/v1/places/${cafe.google_place_id}`, {
      headers: { 'X-Goog-Api-Key': KEY, 'X-Goog-FieldMask': FIELD_MASK },
    });
    const place = await res.json();
    if (place.id) return place;
    console.error(`! ${cafe.name}: place id lookup failed, falling back to search`);
  }

  const res = await fetch('https://places.googleapis.com/v1/places:searchText', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Goog-Api-Key': KEY,
      'X-Goog-FieldMask': FIELD_MASK.split(',').map((f) => `places.${f}`).join(','),
    },
    body: JSON.stringify({
      // Strip our local "(Location)" disambiguator; the address discriminates
      // between same-name chain outlets.
      textQuery: `${cafe.name.replace(/\s*\([^)]*\)\s*/g, ' ').trim()}, ${cafe.address}`,
      maxResultCount: 1,
    }),
  });
  return (await res.json()).places?.[0] ?? null;
}

const q = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`);

const cafes = JSON.parse(fs.readFileSync(0, 'utf8'));
let sql = '-- Generated by scripts/sync-places.mjs\n\n';

for (const cafe of cafes) {
  const place = await lookup(cafe);
  if (!place) {
    console.error(`! ${cafe.name}: no match, skipped`);
    continue;
  }

  const photoUrl = place.photos?.length ? await resolvePhoto(place.photos[0].name) : null;

  sql += `update public.cafes set
  google_place_id = ${q(place.id)},
  address = ${q(place.formattedAddress.replace(/, Canada$/, ''))},
  location = extensions.st_setsrid(extensions.st_makepoint(${place.location.longitude}, ${place.location.latitude}), 4326),${
    photoUrl ? `\n  photo_url = ${q(photoUrl)},` : ''
  }
  rating = ${place.rating ?? 'null'},
  user_ratings_total = ${place.userRatingCount ?? 'null'},
  website = ${q(place.websiteUri)},
  phone = ${q(place.nationalPhoneNumber)}
where id = ${q(cafe.id)};\n\n`;

  console.error(`✓ ${cafe.name}${photoUrl ? '' : ' (no photo)'}`);
}

process.stdout.write(sql);
